.TL
Den sardinske puckelryggens hegemoni \[em] Egemonia 
.AU
Sigfrid Lundberg*
.FS *
Docent i teoretisk ekologi vid Lunds universitet.
Sedermera mjukvaruutvecklare.
Som pensionär masterstudent i teoretisk filosofi i Lund.
.br
\f[CR]https://orcid.org/0009-0006-2612-3203\f[P]
.FE
.RD

.vs 12
.ps 10
Vi som satts att leva i besvikelsens epok
– ja, vad gör vi nu? Vad ska vi tala på för språk?
Ett sätt är att, även om det blåser lite kallt,
tro på det vi trodde på – trots allt!\**
.FS
Kuplett av.
.[ 
#
Danielsson Alfredson 1976
.]
Originaltext och musik: Gloria Sklerov & Henry Lloyd (\[rq]Where Did They Go?\[rq]). 
.FE
.DE
.section
Allt ändras med tiden.
Platon (428 \[en] 348 f.Kr.) var en av dem som tidigt etablerade tanken på hur samhällen förändras till det
.I sämre .
Ett samhälles statsskick utvecklas från aristokrati till timokrati.
Därifrån går det utför till oligarki, demokrati och slutligen tyranni.
.[ (
Plato Cooper
.], Rep. VIII 545c-d)
.PP
Notera att först i listan kommer aristokrati.
Det är den gyllene tidsåldern styrd av visa män,
varje steg från den är ett steg från rättvisa, lag och rätt.
Timokratin uppkommer ur aristokratin genom att härskarna byter sin visdom mot girighet. 
Därefter blir det värre och värre.
Det sluttande planet mynnar ut i tyranni.
Platon hade inte samma syn på demokrati som vi hade i det 20:e och nog faktiskt fortfarande har i det 21:a århundradet;
demokratin innebar för Platon nära nog ett pöbelvälde.
Ett samhälle styrt av sina busar.
.PP
Det är lätt att falla in i tankar som att \f[I]allt var bättre förr\f[P].
Därifrån kan man se lösningen i att låta några få \f[I]starka män\f[P] styra och till slut ser man fördelarna i att låta allt styras av en tyrann.
Starka män som Donald Trump, Viktor Orbán, Vladimir Putin eller Bibi Netanyahu.
Lägg till eller dra ifrån namn från listan, allt efter tycke och smak.
.PP
För mig är det annorlunda.
Jag tycker att den stora skillnaden mellan nutid och alla de dåtider som jag genomlevt är att allt nu känns allt mer motsägelsefullt än det brukade göra.
Det känns inte bättre eller sämre nu än förr.
.PP
Här kommer en motsägelse jag har haft svårt att förklara:
Tänk dig en man,
kalla honom Bill,
pensionär från rostbältet i mellanvästern.
Han har dålig pension.
Han blev kanske arbetslös sent i livet och lyckades aldrig få något välbetalt jobb igen.
Krämporna är dyra att lindra,
för sjukförsäkringen är usel för Bill och andra i hans situation.
Bill röstar på den starke mannen,
tyrannen,
för han är också motståndare till etablissemanget.
\f[I]Drain the swamp\f[P].\**
.FS
Frasen har sitt ursprung i viljan att förebygga malaria under 1800-talet.
Den används numera som en uppmaning att bekämpa korruption i USA.
.[
wikipedia drain swamp
.]
.FE
Tyrannen är rekryterad ur oligarkernas krets.
Han\** kämpar för att ge de andra oligarkerna ränta på vad de investerat för att göra just honom till tyrann.
.FS
Jag utgår ifrån att tyrannen är,
liksom jag,
en ganska tjock vit man i 70-årsåldern.
.FE
Tänk skattelättnader och avregleringar i miljölagstiftning.
Tänk också på hur det är för Anna,
vars arbetskamrat i hemtjänsten Fatima riskerar att utvisas.
Det är enklare att utvisa folk med adress i folkbokföringen och fast jobb,
än att slänga ut dem som gömmer sig och jobbar svart.
.so sympatier-graph.ms
.PP
Oligarki eller tyranni kan naturligtvis uppkomma genom revolt och statskupp,
men oftast har det på senare tid varit genom allmänna val.
Ofta är det Bill och hans olycksbröder som valt tyrannen.
Det är sannolikt inte Anna (se Figur 1).
Dessa är för mig några av de största paradoxerna i samtiden:
Vilka mekanismer får olycksbrödraskapet att rösta bort sin sjukförsäkring för att tillsätta en förhoppningsfull tyrannaspirant,
som dessutom inte ger något annat än retorik i utbyte mot en lagd röstsedel?
Alla demokratiska ledare är valda av folket,
varje tyrann är köpt på sitt eget vis.
.section
.LP
Det finns alldeles för många sådana paradoxer för att jag skall kunna diskutera ens en bråkdel av dem här.
En väldigt tydlig är att ungefär 82 procent av Sveriges folk anser att klimatförändringarna är ett av samtidens stora problem.
.[
krutmeijer 2026
.]
.[
klimat SOM 2026
.]
Det paradoxala är att detta faktum inte sätter några påtagliga avtryck i den politiska processen i landet.
Uppenbarligen är regeringen övertygad om att en klimatfientlig politik kan ge majoritet genom de cirka 18 procent\** som
.I inte
tror att vi behöver göra något åt klimatet.
.FS
För att vara övertydlig: $100 - 82 = 18$.
.FE
.PP
En likartad observation är att det i politik och media ofta påpekas att förtroendet för experter och forskare sjunker,
trots att studier i många länder visar att folks förtroende för forskare och vetenskap är högt.
.[
Pearson 2026
.]
Det visar sig att förtroendet inte sjunker likformigt i hela populationer utan ofta bara i delar av dem.
Ett exempel är att förtroendet för medicinska och naturvetenskapliga forskare i USA sjunker,
i synnerhet bland konservativa och republikanska väljare.
.[
Pearson 2026
.]
Jämför vår fiktive Bill ovan.
.so sympatier.ms
.section
.LP
Antonio Gramsci (1891 \[en] 1937) brukar beskrivas som marxist, historiker, lingvist, filosof och journalist.
Han växte upp i torftiga förhållanden och tvingades lämna universitetet i Turin med en ofärdig utbildning.
1924 \[en] 1926 var han ledare för det italienska kommunistpartiet.
Från 1926 till sin död 1937 hölls han fängslad av Mussolinis fascistiska regim.
.[
Martin James
.]
.PP
Från det att
.[ 
#
Marx Engels 1848
.] 
publicerade sitt Manifest var i princip alla kommunister överens om vilka krafter som styr historiens gång.
Marx och Engels teorier bygger på vad de kallar historiematerialismen,
vilken i sin tur bygger på deras tolkning av Hegels dialektik som beskriver en utvecklingsriktning.
Den går från ett läge till dess motsats, och därifrån till ett slags syntes av de båda lägena.
Krafterna som driver historien framåt är tekniska innovationer som ångmaskiner, dieselmotorer och artificiell intelligens.
Marx kallar dem produktivkrafter.
Även förändringar i produktionens organisation \[em] produktionsförhållandena \[em] spelar roll.
Tillsammans kallas dessa samhällets ekonomiska bas, de är de materiella förutsättningarna för utvecklingen.
Den kulturella utvecklingen äger rum i överbyggnaden,
som innehåller allt som inte har med den materiella produktionen att göra.
Överbyggnaden styrs från basen, och bidrar till att vidmakthålla basen i ett komplext samspel.
.PP
En viktig aspekt av Marx teori är arbetarnas alienation.
Det faktum att arbetaren inte arbetar för sig själv,
inte äger sina redskap och bara får en del av vinsten för sitt arbete gör honom eller henne alienerad.
Det är alienationen som driver fram den socialistiska revolutionen,
säger en mycket kritiserad teori i historiematerialismen.
Den hävdar också att alienationen upphör i det ögonblick den privata äganderätten upphävs.
Som alla vet nu efteråt,
var situationen i det tidiga Sovjetunionen sådan att det inte gick så lätt.
.PP
Ett stort för marxismen var frågan varför proletariatet bara lyckades ta makten i Ryssland och inte i andra länder.
Marx' teorier förutsade att den ekonomiska utvecklingen med arbetarklassens alienering i förhållande till produktivkrafterna var värst i de utvecklade kapitalistiska staterna.
Standardförklaringen var att Tsarryssland var den svagaste länken i den internationella kapitalismen.
Detta är sannolikt kommunistpartiernas bortförklaring av verkligheten.
Två viktiga marxistiska teorier hade falsifierats på bara 10 \[en] 15 år.
.PP
När Mussolinis medhjälpare satte Gramsci i isoleringscell fick han tid till ett forskningsprojekt som bland annat syftade till att förklara varför det bara blev en revolution i ett enda land.
Gramsci redovisade sina resultat i sina delvis hemliga \f[I]Fängelseanteckningar\f[P].
.[
Antonio Gramsci 1967
.]
.[
Antonio Gramsci 1971
.]
Detta är ett svårstuderat fält på grund av att Gramsci skrev avsiktligt dunkelt för att försvåra för fängelsecensuren,
och på grund av att dessa texter blivit väldigt svåra att tolka för hans entusiastiska följare som inte alla är tränade filologer.\**
.FS
Jag är en av dem.
.FE
.section
.LP
Kära läsare,
innan du förkastar vad jag försöker säga för att Antonio Gramsci var kommunist,
och att hans tankar därför borde vara förkastliga:
Problemen han arbetade med var intressanta;
försök att betrakta dem från ett 1920-talsperspektiv snarare än ett vårt 2020-tal.
Hans metod och begreppsapparat används fortfarande ett sekel senare.
I det följande kommer jag att berätta om vad jag har grävt fram om Gramsci.
Mina viktigaste källor är en tolkning av begreppet hegemoni av den tidige
.[ 
#
Gwyn Williams 1960
.].
Den tydlige
.[ 
#
James Martin Gramsci
.] 
är den som förklarat de större linjerna,
men han har också bidragit med biografiska notiser.
Slutligen har jag använt \f[I]En kollektiv intellektuell\f[P] som är ett urval ur \f[I]Anteckningarna i fängelset\f[P] av
.[ 
#
En kollektiv intellektuell
.]
själv.
Jag har också använt en engelsk utgåva
.[
Gramsci Hoare 1971
.]
.PP
Närhelst du ser Gramscis namn,
är chansen stor att det dyker upp tillsammans med substantivet
.I hegemoni ,
som är centralt för Gramsci.
Det förekommer tillsammans med adjektivet
.I kulturell.
Som i kulturell hegemoni.
Termen
.I dominans
finns också i dessa sammanhang.
Man ser den som regel tillsammans med den \[rq]styrande klassen\[rq].
.TS
center tab(;);
l l l .
;dominans;hegemoni
vidmakthålls genom;tvång;samförstånd
samhällsskikt;politiskt samhälle;civilsamhälle
.TE
.PP
Genom den historiska utvecklingen skapas och försvinner grupperingar som står för såväl nöjen som indoktrinering och information.
Gramsci kallar dem
.I intellektuella.
Somliga av dem kan kopplas till den bestående styrande klassen,
de kallas för
.I traditionella
intellektuella.
Det kan vara bildade människor som på olika sätt hjälper till att vidmakthålla samhället.
Lärare, präster, imamer, rabbiner, revisorer och andra kunniga personer knutna till den styrande klassen.
I dag för vi copywriters och influencers till de traditionella intellektuella.
.PP
I civilsamhället finns andra grupperingar som är stadda i tillväxt,
som är kopplade till sina egna intellektuella.
Tidigt på 1900-talet växte det fram frikyrkor som hade pastorer,
fackliga organisationer som utsåg ombudsmän.
Varje subkultur som växer fram och har sin förståsigpåare.
I Gramscis terminologi kallas dessa för organiska intellektuella. 
.TS
center tab(;);
l l l .
;makthavare;maktaspiranter
knutna till;traditionella intellektuella;organiska intellektuella
utvecklas mot;på väg att försvinna;kan vara på väg mot dominans
.TE
.PP
Gramsci beskriver hegemoni som en politisk situation,
eller ett moment.
.[
Gwyn 1960
.]
Det är ett slags jämviktsläge där vissa uppfattningar och sätt att leva har blivit dominerande.
Gramsci är marxist och för honom är det självklart att när något har
.I blivit
orsakas av en eller annan process av de slag vi diskuterat ovan.
Oftast har det skett något i den ekonomiska basen, vilket driver förändringar i hur vi uppfattar världen,
alltså i överbyggnaden.
Detta kan korrelera med att personer rekryteras in i en grupp, ett skrå eller ett företag.
Vissa av dem framträder som representanter för gruppen.
Vi har fått fram en grupp organiska intellektuella i civilsamhället.
.PP
Situationen är inte jämvikt i samma mening som ett dynamiskt system i naturvetenskapen,
där hastigheten varmed alla tillståndsvariabler ändras är noll.
Snarare ett tillstånd som vidmakthålls genom att olika krafter motverkar varandra.
Den gruppering vars intellektuella lyckas styra det offentliga samtalet får kulturell hegemoni,
vilken brukar genomsyra stora delar av civilsamhället inklusive smak, moral, sedvänjor, religion och politik, och sist men inte minst vad som uppfattas som sunt förnuft.
.PP
Gramsci använde sina begrepp för att bygga en modell för hur samhällen kan förändras eller hur en revolution fungerar.
Staten har två samhällsskikt
.EQ
roman "stat" = roman "politiskt samhälle" + roman "civilsamhälle"
.EN
Staten skyddas därför av två lager,
delar av civilsamhällets organiska intellektuella och det politiska samhällets tvångsmekanismer som polis, rättsväsen och militär.
Därutöver finns de traditionella intellektuella (copywriters, influencers...) knutna till den styrande klassen.
Inspirerad av Perry
.[ 
#
anderson antinomies gramsci
.] 
vill jag sammanfatta detta så här
.TS
center tab(;);
l l l .
;öst;väst
civilsamhälle;primitivt / geléartat;utvecklat / robust
stat;dominerande;balanserande
strategi;manöver;position
tempo;snabbhet;utdragenhet
.TE
.LP
Öst representerar här situationen i Ryssland under 1900-talets första år, ungefär fram till första världskriget,
väst speglar situationen i det industrialiserade Europa under samma tid.
Den revolutionära strategin i öst var att uppsöka fienden och med snabba manövrar överta makten över såväl stat som civilsamhälle.
Väst hade då redan utvecklade civilsamhällen.
Arbetarklassen deltog i staten genom valda representanter i parlamentet, Gramsci själv var ledamot av deputeradekammaren.
.PP
Gramsci beskriver strategin i väst med begreppet position,
som antyder att revolutionen i där mer liknar ett skyttegravskrig där parterna håller sina positioner snarare än att de uppsöker varandra genom olika manövrar.
.PP
Vi kan härleda många sätt socialistiska revolutioner kan misslyckas på ur tabellen ovan.
Bland de viktigaste är kanske att civilsamhället kan leda fram till samförståndslösningar.
Det kan också vara så att revolutionen helt enkelt pågår.
Parterna kan ha intagit sina positioner och att vi är inne i ett utdraget positionskrig.
Förmodligen kan ett sådant tillstånd vidmakthållas länge om en gynnsam saltsjöbadsanda genomsyrar civilsamhället.
.PP
Det är ett annat problem som sannolikt är mer akut för Gramsci personligen än varför revolutionerna i väst misslyckades (trots att han var gift med en ryska och att han levt något år i Moskva).
Mussolini tog makten 1922 och för jämnt ett sekel sedan arresterades Gramsci, och sedan ägnade han sig åt sitt projekt så länge han orkade innan han avled i fängelset.
Varför lyckas fascismen?
.PP
Gramsci tänker sig ett tillstånd liknande positionskriget vi diskuterade ovan.
Vi har en progressiv kraft $A$ och en regressiv $B$ i balans så tillvida att ingen av dem kan ta makten.
I det läget kommer en tredje aktör $C$ som representerar vad Gramsci kallar
.I Caesarismen .
Den är ett uttryck för den italienska fascismens önskan att återupprätta det gamla Rom.
Gramsci kan naturligtvis inte nämna sina samtida motståndare vid namn.
Han kan inte nämna Benito Mussolini,
därför diskuterar han Julius Caesar, Napoleon Bonaparte (både I och III), Otto von Bismarck och Oliver Cromwell för att bara nämna några.
Vi har på scenen alltså:
.TS
center tab(;);
l l l l .
kraft;A;B;C
inriktning;progressiv;regressiv;fascistisk/progressiv/regressiv
.TE
Så här beskriver Gramsci vad som händer:
.QP
.vs 12
.ps 10
Man kan säga att caesarismen uttrycker en situation,
där de kämpande krafterna på ett katastrofalt sätt uppväger varandra,
dvs de väger så jämnt att den fortsatta striden inte kan sluta annat än med ömsesidig förintelse.
När den progressiva kraften $A$ kämpar mot den regressiva kraften $B$ kan det inte bara inträffa att $A$ besegrar $B$ eller att $B$ besegrar $A$,
det kan också inträffa att varken $A$ eller $B$ vinner utan bara får varandra att förblöda och att en tredje kraft $C$ ingriper utifrån och lägger under sig vad som återstår av $A$ och $B$.
I Italien var det just detta som inträffade efter il Magnificos\** död.
.[ (
En kollektiv intellektuell
.], s. 256)
.FS
Lorenzo de' Medici (känd som Lorenzo il Magnifico), 1449 \[en] 1492.
.FE
.LP
Den caesaristiska kraften tar sig alltså in från sidan och roffar åt sig makten.
Denna kraft C kan ha olika inriktning,
beroende på ifall den ger sitt stöd åt A eller B.
Gramsci beskriver Caesar och Napoleon I som progressiva,
medan Napoleon III och Bismarck är regressiva.
.[ (
En kollektiv intellektuell
.], s. 256)
Jag antar att den i vilket fall kan vara mer eller mindre fascistisk.
.section
.LP
Ett halvsekel efter att Gramski arrestades spelade AB Svenska Ord revyn \f[I]Svea Hund\f[P] på Göta Lejon i Stockholm.
Monica Zetterlund sjöng då \f[I]Var blev ni av, ljuva drömmar\f[P]?
\
.[
alfredson danielsson 1976
.]
.ID
.vs 12
.ps 10
Svara, du med röda stjärnan på din vårkavaj:
alla tåg som går mot lyckans land på första maj
\[em] svara på en fråga från en vän som tappat tron:
när är dom framme vid sin slutstation?
.DE
I Storbritannien skulle Margaret Thatcher bli premiärminister tre år senare.
Stuart Hall skrev sin med rätta berömda \[rq]The great moving right show\[rq].
.[
stuart hall 1979
.]
Detta var en tid med mycket rörelse:
1981 tillträdde Ronald Reagan som USA:s 40:de president.
1973 begick Salvador Allende självmord efter militärkuppen i Chile.
Sist men inte minst så föll Saigon den 30 april 1975 och med det tog Vietnamkriget slut.
Den minneskunnige erinrar sig säkert fler händelser.
Som exempelvis folkomröstningen om kärnkraftens framtid i Sverige 1980.
.PP
Ett nästan jämnt sekel efter Gramscis arrestering är det mellanårsval i USA och alla undrar hur det skall gå.
Karl Marx skrev att historien upprepar sig två gånger,
först som tragedi och sedan som fars.
Det är lätt att se detta som en djup sanning när man betraktar Donald Trump, som är en riktig pajas.
Tyvärr sätter sig mitt skratt i vrångstrupen,
och Andy
.[ 
#
Andy Knott 2020
.] 
kände sig föranledd att skriva \[rq]The new moving right show\[rq].
.PP
Hall och Knott behandlar frågan om högersvängarna på aningen olika sätt som rimmar på Gramscis egen,
på så vis att de utgår från olika avsnitt i fängelseanteckningarna.
.section
.LP
Lars Gustafsson myntade uttrycken mediavänstern och problemformuleringsprivilegiet
.[
Gustafsson klassens vakthund
.]
i en rapport 1979 till Svenska Arbetsgivareföreningens (SAF) kongress 1980.
.[
Westholm 2016
.]
Blabla blabla blabla blabla blabla.
Blabla blabla blabla blabla blabla.
.[
daniel rueda 2021
.]
