.KF
.G1
size = 1.8
graph Females
coord x 1800,2010 y 0, 0.008 
frame invis ht 7 wid 8 left solid color "black" bot solid color "black"
label bot "\[oA]r" down 1
label left "Frekvens" left 1.2
# Age   1751-1754       1800-1804       1900-1904       2000-2004 
draw a solid color "black"
draw b solid color "black"
draw c dashed color "black"
draw d dotted color "black"

copy "metapolitics.text" thru {
	next a at $1, $2
}
.G2
.QP
.vs 12
.ps 10
Figure 2.
Frekvensen av ordet \[rq]metapolitics\[rq] i engelska spr\[oa]ket 1800 \[en] 2010.
.[
oxford metapolitics 2024
.]
https://doi.org/10.1093/OED/3638586313
(data h\[:a]mtade 2026-08-04).
.sp
.KE
